services:
  mongodb:
    image: mongo:7.0.5
    container_name: chick-pic-mongodb-img
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: image-service
    volumes:
      - ./data:/data/db